name: camhd_motion_metadata_datapackage
channels:
- defaults
dependencies:
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.2=0
- readline=6.2=2
- setuptools=27.2.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - pycamhd.lazycache
  - pycamhd.motionmetadata
  - cchardet==1.1.3
  - certifi==2017.4.17
  - chardet==3.0.4
  - click==6.7
  - datapackage==0.8.9
  - et-xmlfile==1.0.1
  - future==0.16.0
  - goodtables==1.0.0
  - google-api-python-client==1.6.2
  - httplib2==0.10.3
  - idna==2.5
  - ijson==2.3
  - isodate==0.5.4
  - jdcal==1.3
  - jsonlines==1.1.3
  - jsonschema==2.6.0
  - jsontableschema==0.10.1
  - jsontableschema-bigquery==0.4.3
  - linear-tsv==1.0.0
  - oauth2client==4.1.2
  - openpyxl==2.4.8
  - pyasn1==0.3.1
  - pyasn1-modules==0.0.9
  - python-dateutil==2.6.1
  - python-slugify==1.2.4
  - requests==2.18.2
  - rfc3986==0.4.1
  - rsa==3.4.2
  - six==1.10.0
  - sqlalchemy==1.1.12
  - tabulator==1.1.0
  - unicodecsv==0.14.1
  - unidecode==0.4.21
  - uritemplate==3.0.0
  - urllib3==1.22
  - xlrd==1.0.0
